env:
  browser: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - error
    - args: none
  quotes:
    - error
    - single
  semi:
    - error
    - always
